services:
  # Backend (Express.js)
  backend:
    build:
      context: ./backend
    container_name: mistamluvi_backend
    ports:
      - "3000:3000" # Zpřístupní backend na localhost:3000
    volumes:
      # Propojí složku 'data' na vašem disku se složkou v kontejneru
      - ./backend/data:/app/data
    env_file: ./backend/.env
    restart: unless-stopped
    networks:
      edge:
        aliases:
          - mistamluvi_backend

  # Frontend (React + Nginx)
  frontend:
    build:
      context: ./frontend
    container_name: mistamluvi_frontend
    ports:
      - "8080:80" # Zpřístupní frontend na localhost:8080
    env_file: ./frontend/.env
    restart: unless-stopped
    networks:
      edge:
        aliases:
          - mistamluvi_frontend

networks:
    edge:
      external: true